# Generated by Django 3.2.23 on 2024-01-24 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_new_pair_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='confirmation_token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='withdrawalrequest',
            unique_together={('user', 'confirmation_token')},
        ),
    ]
