# Generated by Django 3.2.23 on 2024-01-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240124_0608'),
        ('cryptocoins', '0004_auto_20230607_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='AahWithdrawalApprove',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawalrequest',),
        ),
        migrations.CreateModel(
            name='MaticWithdrawalApprove',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawalrequest',),
        ),
    ]
