# Generated by Django 3.2.23 on 2024-01-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240124_0608'),
        ('cryptocoins', '0005_aahwithdrawalapprove_maticwithdrawalapprove'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlayWithdrawalApprove',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawalrequest',),
        ),
    ]
