# Generated by Django 3.2.23 on 2024-02-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240124_0608'),
        ('cryptocoins', '0006_klaywithdrawalapprove'),
    ]

    operations = [
        migrations.CreateModel(
            name='C4eiWithdrawalApprove',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawalrequest',),
        ),
    ]
